# Reference
# https://qiita.com/faronan/items/d99132950b61753050d3#7-cloud-run%E3%81%B8%E3%81%AE%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4
# https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run?hl=ja#cloud-run_2
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/text-sonic:$COMMIT_SHA',
        './',
        '-f',
        'Dockerfile',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/text-sonic:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'text-sonic'
      - '--image'
      - 'gcr.io/$PROJECT_ID/text-sonic:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
images:
  - 'gcr.io/$PROJECT_ID/text-sonic:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
