"""Added script column

Revision ID: 6ab0cda29462
Revises: af1e925c2ee8
Create Date: 2023-11-13 15:28:37.160541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ab0cda29462"
down_revision: Union[str, None] = "af1e925c2ee8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("writing", sa.Column("script", sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("writing", "script")
    # ### end Alembic commands ###
