"""Added scripts column

Revision ID: af1e925c2ee8
Revises: 
Create Date: 2023-11-13 01:17:09.499727

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "af1e925c2ee8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index("ix_writing_script_id", table_name="writing_script")
    # op.drop_table("writing_script")
    # op.add_column("writing", sa.Column("scripts", mysql.JSON(), nullable=False))
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("writing", "scripts")
    # op.create_table(
    #     "writing_script",
    #     sa.Column("id", mysql.VARCHAR(length=36), nullable=False),
    #     sa.Column("scripts", mysql.JSON(), nullable=False),
    #     sa.Column("created_at", mysql.DATETIME(), nullable=True),
    #     sa.Column("updated_at", mysql.DATETIME(), nullable=True),
    #     sa.PrimaryKeyConstraint("id"),
    #     mysql_collate="utf8mb4_0900_ai_ci",
    #     mysql_default_charset="utf8mb4",
    #     mysql_engine="InnoDB",
    # )
    # op.create_index("ix_writing_script_id", "writing_script", ["id"], unique=False)
    # ### end Alembic commands ###
    pass
